### ISSUE TITLE
Error- mdx-bundler not supported

### ISSUE THREAD

**Issue by paruladitya** [timlrx/tailwind-nextjs-starter-blog#144]
This error occurs in windows 10, but works perfectly in mac.
When any mdx related page(about, blog) is opened the app crashes with the following error-
``` 
Error: Not supported
    at bundleMDX (C:\projects\tailwind-nextjs-starter-blog\node_modules\mdx-bundler\dist\index.js:60:27)
    at getFileBySlug (C:\projects\tailwind-nextjs-starter-blog\.next\server\pages\about.js:2427:67)
    at getStaticProps (C:\projects\tailwind-nextjs-starter-blog\.next\server\pages\about.js:5933:86)
    at renderToHTML (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\next-server\server\render.js:27:1786)
    at async C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\next-server\server\next-server.js:112:97
    at async __wrapper (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\next-server\server\next-server.js:137:387)
    at async DevServer.renderToHTML (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\next-server\server\next-server.js:138:610)
    at async DevServer.renderToHTML (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\server\next-dev-server.js:36:578)
    at async DevServer.render (C:\projects\tailwind-nextjs-starter-blog\node_modules\next\dist\next-server\server\next-server.js:75:160)

**Comment by timlrx** [comment]
I don't get any errors while developing or building on windows 10. Try deleting your node_modules and re-installing the dependencies.

**Comment by burhanuday** [comment]
Looks related to this
Have opened an issue in related repo - https://github.com/wooorm/xdm/issues/72

```
file:///home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/xdm/lib/plugin/remark-mdx.js:14
import {fromMarkdown, toMarkdown} from 'mdast-util-mdx'
                      ^^^^^^^^^^
SyntaxError: The requested module 'mdast-util-mdx' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'mdast-util-mdx';
const {fromMarkdown, toMarkdown} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async bundleMDX (/home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/mdx-bundler/dist/index.js:60:27)
    at async getFileBySlug (webpack-internal:///./lib/mdx.js:83:7)
    at async getStaticProps (webpack-internal:///./pages/blog/[...slug].js:42:16)
    at async renderToHTML (/home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/next/dist/next-server/server/render.js:27:1780)
    at async /home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/home/burhanuday/burhan/projects/portfolio-and-blog/node_modules/next/dist/next-server/server/next-server.js:137:387)
```

**Comment by burhanuday** [comment]
![image](https://user-images.githubusercontent.com/25934701/126672107-527927ab-cbda-4d3c-8620-1219868c2f52.png)

**Comment by timlrx** [comment]
I think this is a different issue but if you are using different package versions from what I specified, you might run into such problems as nextjs currently does not support esm but most of wooorm's packages only support esm, without cjs

**Comment by burhanuday** [comment]
Both error messages fail at the same exact `bundleMDX` method
I tried cloning the repo and running without making any changes at all and I still get this error

**Comment by timlrx** [comment]
What OS and node version are you using?

In your post on xdm, you mentioned that "it's a NextJS project which uses Webpack 5 with the ESM module loader enabled". How are you enabling ESM? nextjs 11.0.1 does not support esm

If your repository is on github, I will take a closer look at it.

**Comment by burhanuday** [comment]
OS: Linux
Node: v12.19.0

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
event - build page: /blog/[...slug]
wait  - compiling...
event - compiled successfully
(node:121539) ExperimentalWarning: The ESM module loader is experimental.
```

I see this output when the server starts. the last line talks about the ESM module loader from NodeJS. My repository is not public but it fails for me even on a fresh clone of the repo

if you are using a different Node version do let me know. I will test it on the same Node version

I first thought it was an issue of dependencies between our lock files but I have even tried `npm ci` for installing dependencies so that I get the exact same deps tree as you. still fails with the same error.

Also tried adding `webpack5: false` to the next config thinking that its probably caused by Webpack 5. Failed on that as well

**Comment by timlrx** [comment]
The latest version of node 12 or node 14 works for me. Maybe try upgrading your node version? I do not get this error message: "(node:121539) ExperimentalWarning: The ESM module loader is experimental."

**Comment by timlrx** [comment]
A fresh clone of the master works for me, so it's probably system related. I tried with node v12.22.3 (npm v6.14.13) and node v14.16.1 (npm v6.14.12)

**Comment by burhanuday** [comment]
Will test with the mentioned node versions and revert back to you

**Comment by burhanuday** [comment]
confirmed working on version `v14.16.1`. Seems like node version was the issue for me. thank you

**Comment by omaralsoudanii** [comment]
@timlrx 

nextjs enabling esm support by default. Currently its hidden behind an experimental flag, which the OP definitely added otherwise you won't see any esm related messages from nextjs. See this for more details 

https://twitter.com/timneutkens/status/1414561271953989635?s=19
