### ISSUE TITLE
Vercel not deploying the app

### ISSUE THREAD

**Issue by sasafister** [timlrx/tailwind-nextjs-starter-blog#201]
**Describe the bug**
Vercel is not working properly

**To Reproduce**
Deploying app from gitlab fails with this error. Locally when `npm run build` is triggered, app is builded properly.

```
info  - Compiled successfully
14:36:44.574
info  - Collecting page data...
14:36:45.605
info  - Generating static pages (0/23)
14:36:46.773
info  - Generating static pages (5/23)
14:36:46.833
/vercel/path0/node_modules/esbuild/bin/esbuild: /vercel/path0/node_modules/esbuild/bin/esbuild: cannot execute binary file
14:36:46.848
events.js:377
14:36:46.849
      throw er; // Unhandled 'error' event
14:36:46.849
      ^
14:36:46.849
14:36:46.849
Error: write EPIPE
14:36:46.849
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
14:36:46.849
    at writeGeneric (internal/stream_base_commons.js:147:3)
14:36:46.849
    at Socket._writeGeneric (net.js:787:11)
14:36:46.849
    at Socket._write (net.js:799:8)
14:36:46.850
    at writeOrBuffer (internal/streams/writable.js:358:12)
14:36:46.850
    at Socket.Writable.write (internal/streams/writable.js:303:10)
14:36:46.850
    at Object.writeToStdin (/vercel/path0/node_modules/esbuild/lib/main.js:1723:19)
14:36:46.850
    at sendRequest (/vercel/path0/node_modules/esbuild/lib/main.js:617:14)
14:36:46.850
    at buildOrServeContinue (/vercel/path0/node_modules/esbuild/lib/main.js:1213:5)
14:36:46.850
    at /vercel/path0/node_modules/esbuild/lib/main.js:1029:13
14:36:46.850
Emitted 'error' event on Socket instance at:
14:36:46.850
    at emitErrorNT (internal/streams/destroy.js:106:8)
14:36:46.850
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
14:36:46.850
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
14:36:46.850
  errno: -32,
14:36:46.850
  code: 'EPIPE',
14:36:46.850
  syscall: 'write'
14:36:46.851
}
14:36:46.874
14:36:46.874
> Build error occurred
14:36:46.877
Error: Call retries were exceeded
14:36:46.877
    at ChildProcessWorker.initialize (/vercel/path0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
14:36:46.878
    at ChildProcessWorker._onExit (/vercel/path0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:275:12)
14:36:46.878
    at ChildProcess.emit (events.js:400:28)
14:36:46.879
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
14:36:46.879
  type: 'WorkerError'
14:36:46.879
}
14:36:46.924
Error: Command "npm run build" exited with 1
```

**Comment by timlrx** [comment]
Hi, is this a fresh clone or your own repo? If it's a fresh clone, I can't think of a possible solution other than try clearing the cache on vercel and do a fresh deploy?

**Comment by sasafister** [comment]
I did clean install and it works, but images are not showing when sharing. og:image is there but the file is not, it throws 404 when I want to grab direct link to the image.

https://next-test-472voxji8-sashafishter.vercel.app/blog/nova-sezona-novi-rekordi

**Comment by sasafister** [comment]
Got it.. I didn't specify the siteUrl in the siteMedata.js
