### ISSUE TITLE
Got errors when starting the app

### ISSUE THREAD

**Issue by nvdai2401** [timlrx/tailwind-nextjs-starter-blog#237]
Hi! Thank you for the great project!

**Describe the bug**
I cannot start the app and get errors like the screenshot below.

**To Reproduce**
1. Go to the repo home page
2. Click on `Use this template` button
3. Clone the repo after step 2
4. On my local machine, open the app folder, remove `package-lock.json`. Then run `yarn`
5. Run `yarn dev`

**Expected behavior**
Can start the app without any error

**Screenshots**

<img width="1335" alt="Screen Shot 2021-09-09 at 21 53 16" src="https://user-images.githubusercontent.com/33539569/132710152-4d031959-0dca-4aa8-90bb-de70ee0131c1.png">

**System Info (if dev / build issue):**
 - OS: macOS 11.3
 - Node version: v12.16.0
 - Npm version: v6.13.4
 - Yarn version: v1.22.10

**Browser Info (if display / formatting issue):**
- Device [e.g. Desktop, iPhone6]

**Additional context**
Logs from my terminal

```
❯ yarn dev      
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
error - unhandledRejection: Error: Not supported
    at Object.unist-util-visit (/my-blog/.next/server/pages/index.js:592:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:20:74)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.hast-util-to-string (/my-blog/.next/server/pages/index.js:284:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/remark-toc-headings.js:9:77)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/remark-toc-headings.js:1:21)
    at Object../lib/remark-toc-headings.js (/my-blog/.next/server/pages/index.js:98:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:26:79)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.unist-util-visit (/my-blog/.next/server/pages/index.js:592:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:20:74)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.unist-util-visit (/my-blog/.next/server/pages/index.js:592:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:20:74)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.rehype-katex (/my-blog/.next/server/pages/index.js:526:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:30:71)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.rehype-prism-plus (/my-blog/.next/server/pages/index.js:537:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:31:76)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.rehype-autolink-headings (/my-blog/.next/server/pages/index.js:515:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:29:83)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.rehype-slug (/my-blog/.next/server/pages/index.js:548:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:28:70)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.remark-math (/my-blog/.next/server/pages/index.js:581:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:24:69)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.remark-footnotes (/my-blog/.next/server/pages/index.js:559:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:23:74)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.remark-gfm (/my-blog/.next/server/pages/index.js:570:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:22:68)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
error - unhandledRejection: Error: Not supported
    at Object.unist-util-visit (/my-blog/.next/server/pages/index.js:592:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:20:74)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
event - compiled successfully
error - Error: Not supported
    at Object.rehype-prism-plus (/my-blog/.next/server/pages/index.js:537:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/mdx.js:31:76)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./lib/mdx.js:1:21)
    at Object../lib/mdx.js (/my-blog/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/my-blog/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:12:66)
    at Function.__webpack_require__.a (/my-blog/.next/server/webpack-runtime.js:106:13)
    at eval (webpack-internal:///./pages/index.js:1:21) {
  page: '/'
}
```

**Comment by timlrx** [comment]
Try upgrading to the latest node 12 or use node 14

**Comment by nvdai2401** [comment]
I can run the app after upgrading to node 14. Thank you!
