### ISSUE TITLE
Mail chimp email sign up doesn't work. 

### ISSUE THREAD

**Issue by blazestudios23** [timlrx/tailwind-nextjs-starter-blog#680]
**Describe the bug**

I've added the env vars for mail chimp. I use the component to try to sign up to the email. It does nothing. 

**To Reproduce**

I used this component: 

```React
<BlogNewsletterForm title="Sign Up" />
```

with these env vars filled in: 

```
MAILCHIMP_API_KEY=
MAILCHIMP_API_SERVER=
MAILCHIMP_AUDIENCE_ID=
```

I get the following error even when using a valid email:

```
Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
Failed to load resource: the server responded with a status of 404 ()
```
**Expected behavior**

One should be able to sign up to get emails. 

**Screenshots**

<img width="1331" alt="Screenshot 2023-08-14 at 9 21 25 AM" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/5480874/1795f18d-4b6f-43f7-a634-0380b4694675">

<img width="554" alt="Screenshot 2023-08-14 at 9 22 22 AM" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/5480874/ce6800b4-702c-4211-a862-ba420cad3adb">

**System 
This is deploying to verbal with all default settings. 

**Browser Info (if display / formatting issue):**

- Device safari, on a Mac, as well as on a Phone. 
- Browser safari
- Version I have this error and I've had my users also complain about this error. 

**Additional context**

**Comment by timlrx** [comment]
Just tried it out and it works for me. Do note that if you had generated the api key from mailchimp's platform, it takes the form of `xxxxxxxxx-us3`. `xxxxxxxxx` corresponds to `MAILCHIMP_API_KEY` and `us3` should be the value of `MAILCHIMP_API_SERVER`.

**Comment by blazestudios23** [comment]
My id has ```xxxxx-us21```  I tried with us3 as well. 

I get this error from my local env:

```
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.origSetHeader [as setHeader] (node:_http_outgoing:645:11)
    at ServerResponse.setHeader (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/base-server.ts:471:16)
    at sendJson (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/api-utils/node.ts:264:7)
    at ServerResponse.apiRes.json (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/api-utils/node.ts:508:29)
    at NewsletterHandler (webpack-internal:///(api)/./node_modules/pliny/chunk-3QSZ5LSS.js:53:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at eval (webpack-internal:///(api)/./node_modules/pliny/chunk-3QSZ5LSS.js:58:32)
    at Object.apiResolver (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/api-utils/node.ts:531:5)
    at DevServer.runApi (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/next-server.ts:800:5)
    at Object.fn (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/next-server.ts:1209:27)
    at Router.execute (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/router.ts:457:26)
    at DevServer.run (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/base-server.ts:849:23)
    at DevServer.run (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/dev/next-dev-server.ts:1037:14)
    at DevServer.handleRequest (/Users/andrewobrigewitsch/Documents/Work.nosync/full-stack-blog/node_modules/src/server/base-server.ts:752:14) {
  code: 'ERR_HTTP_HEADERS_SENT',
  page: '/api/newsletter'
}
```

**Comment by timlrx** [comment]
If your id is `xxxxx-us21`, that means `xxxxx` should be assigned to `MAILCHIMP_API_KEY` and `us21` to `MAILCHIMP_API_SERVER`.

**Comment by blazestudios23** [comment]
I tried this:

```env
MAILCHIMP_API_KEY=xxxxxxxxxxxxxxxx
MAILCHIMP_API_SERVER=us21
MAILCHIMP_AUDIENCE_ID=xxxxxx
```

I still get the same error.

**Comment by danieldanielecki** [comment]
> I tried this:
> 
> MAILCHIMP_API_KEY=xxxxxxxxxxxxxxxx
> MAILCHIMP_API_SERVER=us21
> MAILCHIMP_AUDIENCE_ID=xxxxxx
> I still get the same error.

same for me, debugging... my blog https://blog.ditectrev.com and the repository https://github.com/Ditectrev/blog

I've put them in secrets, and deployed, but on localhost I couldn't get it working either with the values taken from `.env`.

<img width="1017" height="392" alt="Image" src="https://github.com/user-attachments/assets/6ed135a5-8fc9-4648-9eda-e08cda7391a3" />
