### ISSUE TITLE
Error: The provided export path '/tags' doesn't match the '/tags/[tag]' page.

### ISSUE THREAD

**Issue by yuis-ice** [timlrx/tailwind-nextjs-starter-blog#752]
**Describe the bug**

```
$ npm run build

> tailwind-nextjs-starter-blog@2.0.2 build
> cross-env INIT_CWD=$PWD next build && cross-env NODE_OPTIONS='--experimental-json-modules' node ./scripts/postbuild.mjs

successCallback /home/yuis/pg/tailwind-nextjs-starter-blog/.contentlayer
(node:942800) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:942800) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
Local search index generated...
Generated 42 documents in .contentlayer
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types  .. ⚠ TypeScript project references are not fully supported. Attempting to build in incremental mode.
 ✓ Checking validity of types    
 ✓ Collecting page data    
   Generating static pages (10/137) [==  ] 

Error occurred prerendering page "/tags". Read more: https://nextjs.org/docs/messages/prerender-error
Error: The provided export path '/tags' doesn't match the '/tags/[tag]' page.
Read more: https://nextjs.org/docs/messages/export-path-mismatch
    at getParams (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/export/helpers/get-params.js:27:15)
    at exportPageImpl (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/export/worker.js:91:47)
    at /home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/export/worker.js:219:22
    at Span.traceAsyncFn (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/trace/trace.js:105:26)
    at Object.exportPage (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/export/worker.js:218:41)
    at execFunction (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2764)
    at execHelper (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2422)
    at execMethod (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2510)
    at process.messageListener (/home/yuis/pg/tailwind-nextjs-starter-blog/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1228)
 ✓ Generating static pages (137/137) 

> Export encountered errors on following paths:
        /tags/[tag]/page: /tags
```

**System Info (if dev / build issue):**

Ubuntu 20.04

- Node version (please ensure you are using 18+)

v20.8.1

- Npm version

10.1.0

**Additional context**

`npm run dev` works no problem, the error started to happen after added some tens of post pages then tried build. The build step passes sometimes, but fails like 3/5 times.

**Comment by timlrx** [comment]
So you are saying sometimes the build step succeeds and other times it fails with the above error message? Could you share a link to the repo?
